"""Tests for tools/manifest.py: `--check` passes only on the exact generated bytes.

    python -m unittest discover -s tools -p "*_test.py"

Standard library only.
"""

from __future__ import annotations

import pathlib
import sys
import tempfile
import unittest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import manifest  # noqa: E402  (the tool lives beside this test, not in a package)


class ManifestCheckTest(unittest.TestCase):
    def setUp(self) -> None:
        self._temp = tempfile.TemporaryDirectory()
        self.addon = pathlib.Path(self._temp.name) / "addon"
        (self.addon / "core").mkdir(parents=True)
        (self.addon / "a.txt").write_bytes(b"alpha\n")
        (self.addon / "core" / "b.gd").write_bytes(b"beta\n")
        (self.addon / "c.md").write_bytes(b"gamma\n")
        (self.addon / "core" / "b.gd.uid").write_bytes(b"uid://ignored\n")
        self._write(manifest.build(self.addon))

    def tearDown(self) -> None:
        self._temp.cleanup()

    def _write(self, text: str) -> None:
        (self.addon / manifest.MANIFEST_NAME).write_bytes(text.encode("utf-8"))

    def _lines(self) -> list[str]:
        return manifest.build(self.addon).splitlines()

    def _problems(self) -> list[str]:
        return manifest.check(self.addon)

    def test_the_generated_manifest_passes(self) -> None:
        self.assertEqual(self._problems(), [])
        self.assertEqual(len(self._lines()), 3, "import artefacts are not listed")

    def test_reordered_lines_fail(self) -> None:
        lines = self._lines()
        lines[0], lines[1] = lines[1], lines[0]
        self._write("\n".join(lines) + "\n")
        problems = self._problems()
        self.assertTrue(problems)
        self.assertTrue(any("out of order" in problem for problem in problems), problems)

    def test_a_duplicated_line_fails(self) -> None:
        lines = self._lines()
        self._write("\n".join(lines + [lines[0]]) + "\n")
        problems = self._problems()
        self.assertTrue(any(problem.startswith("duplicate:") for problem in problems), problems)

    def test_a_changed_hash_fails(self) -> None:
        (self.addon / "a.txt").write_bytes(b"alpha, edited\n")
        self.assertEqual(self._problems(), ["changed: a.txt"])

    def test_an_added_file_fails(self) -> None:
        (self.addon / "core" / "d.gd").write_bytes(b"delta\n")
        self.assertEqual(self._problems(), ["not listed: core/d.gd"])

    def test_a_removed_file_fails(self) -> None:
        (self.addon / "c.md").unlink()
        self.assertEqual(self._problems(), ["listed but missing: c.md"])

    def test_a_blank_line_fails(self) -> None:
        lines = self._lines()
        self._write("\n".join([lines[0], "", *lines[1:]]) + "\n")
        problems = self._problems()
        self.assertEqual(len(problems), 1, problems)
        self.assertIn("whitespace", problems[0])

    def test_cr_line_endings_fail(self) -> None:
        self._write(manifest.build(self.addon).replace("\n", "\r\n"))
        problems = self._problems()
        self.assertTrue(any("CR line endings" in problem for problem in problems), problems)

    def test_a_missing_manifest_fails(self) -> None:
        (self.addon / manifest.MANIFEST_NAME).unlink()
        self.assertEqual(len(self._problems()), 1)


if __name__ == "__main__":
    unittest.main()
